### ISSUE TITLE
Error while creating deployment 

### ISSUE THREAD

**Issue by rohits-splunk** [font/k8s-example-apps#9]
kubectl create -f deployments/mongo-deployment.yaml

error: resource mapping not found for name: "mongo" namespace: "" from "deployments/mongo-deployment.yaml": no matches for kind "Deployment" in version "extensions/v1beta1"
ensure CRDs are installed first

**Comment by font** [comment]
Thanks for reporting the issue! These manifests are a bit outdated as the `Deployment` API group has since been updated to `apps/v1`. If you try to replace `extensions/v1beta1` with `apps/v1` the error should be fixed.

**Comment by rohits-splunk** [comment]
I fixed it , thanks @font . Would you mind telling which mongo db version this app expects ? I installed the latest one and the app is complaining about.

**Comment by font** [comment]
> I fixed it , thanks @font . Would you mind telling which mongo db version this app expects ? I installed the latest one and the app is complaining about.

Great question! The YAML manifests should really have specified the exact mongo version by tagging the image. At the time it wasn't an issue because any mongo version worked since it didn't rely on any unique mongo features. It was [mongo 3.4](https://www.mongodb.com/docs/v3.4/) at the time.

In any case, make sure to align the [MongoDB NodeJS driver version used in pacman](https://github.com/font/pacman/blob/master/package.json#L16) with a MongoDB version that is [compatible](https://www.mongodb.com/docs/drivers/node/current/compatibility/).

**Comment by rohits-splunk** [comment]
I am trying to install 3.4 but it wont install at all, because exact versions of other components are not know, then i tried 3.2 by following the link https://www.mongodb.com/docs/v3.2/tutorial/install-mongodb-on-ubuntu/ and it again failed due do dependencies. 

Is there a possibility to upgrade the mongo used in the game along with the drivers ?

**Comment by aespindola09** [comment]
To solve the version problem I ran the following commands to change the apiVersion and add the selector in the deployments

```
#Remplace apiVersion extensions/v1beta1 for apps/v1 for compatibility 
# Add selector name mongo
cat > deployments/mongo-deployment.yaml <<EOF
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: mongo
  name: mongo
spec:
  replicas: 0
  selector:
    matchLabels:
      name: mongo
  template:
    metadata:
      labels:
        name: mongo
    spec:
      containers:
      - image: mongo
        name: mongo
        ports:
        - name: mongo
          containerPort: 27017
        volumeMounts:
          - name: mongo-db
            mountPath: /data/db
      volumes:
        - name: mongo-db
          persistentVolumeClaim:
            claimName: mongo-storage
EOF


#Remplace apiVersion extensions/v1beta1 for apps/v1 for compatibility
# Add selector name pacman
cat > deployments/pacman-deployment.yaml <<EOF
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: pacman
  name: pacman
spec:
  replicas: 0
  selector:
    matchLabels:
      name: pacman
  template:
    metadata:
      labels:
        name: pacman
    spec:
      containers:
      - image: quay.io/ifont/pacman-nodejs-app:latest
        name: pacman
        ports:
        - containerPort: 8080
          name: http-server
EOF
```
